version: '3.3'
services:
        mydb:
                image: mariadb:10.4.6
                restart: always
                environment:
                        - MYSQL_ROOT_PASSWORD=123456
                        - MYSQL_DATABASE=appdb
                volumes:
                        - ./db-data:/var/lib/mysql
                ports:
                        - '3306:3306'
