FROM openjdk:11

#MAINTAINER gwangmin.lim <rhdl142@danawa.com>

COPY todo-docker-spring-0.0.1-SNAPSHOT.jar todo-docker-spring-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "todo-docker-spring-0.0.1-SNAPSHOT.jar"]

