version: "3.3"
services:
        es1:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
                container_name: es1
                ports:
                        - 9200:9200
                        - 9300:9300
                environment:
                        - node.name=es1
                        - cluster.name=es-docker-cluster
                        - discovery.seed_hosts=es1,es2,es3
                        - cluster.initial_master_nodes=es1,es2,es3
                        - node.roles=data,master
                          #- bootstrap.memory_lock=true
                          #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                volumes:
                        - /home/danawa/volumes/data01:/usr/share/elasticsearch/data
                networks:
                        - elastic-net
        es2:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
                container_name: es2
                ports:
                        - 9201:9200
                        - 9301:9300
                environment:
                        - node.name=es2
                        - cluster.name=es-docker-cluster
                        - discovery.seed_hosts=es1,es2,es3
                        - cluster.initial_master_nodes=es1,es2,es3
                        - node.roles=data,master
                          #- bootstrap.memory_lock=true
                          #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                volumes:
                        - /home/danawa/volumes/data02:/usr/share/elasticsearch/data
                networks:
                        - elastic-net
        es3:
                image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
                container_name: es3
                ports:
                        - 9202:9200
                        - 9302:9300
                environment:
                        - node.name=es2
                        - cluster.name=es-docker-cluster
                        - discovery.seed_hosts=es1,es2,es3
                        - cluster.initial_master_nodes=es1,es2,es3
                        - node.roles=data
                          #- bootstrap.memory_lock=true
                          #- "ES_JAVA_OPTS=-Xms512m -Xmx512m"
                ulimits:
                        memlock:
                                soft: -1
                                hard: -1
                volumes:
                        - /home/danawa/volumes/data03:/usr/share/elasticsearch/data
                networks:
                        - elastic-net
        kibana:
                depends_on:
                        - es1
                        - es2
                        - es3
                image: docker.elastic.co/kibana/kibana:7.9.1
                container_name: kibana
                ports:
                        - 5601:5601
                links:
                        - es1:es1
                environment:
                        - server.name=kibana
                        - server.host=0
                        - ELASTICSEARCH_HOSTS=http://es1:9200
                networks:
                        - elastic-net
networks:
        elastic-net: {}
volumes:
        data01:
                driver: local
        data02:
                driver: local
        data03:
                driver: local
