export const SET_DANAWA_KWD_DICT = 'SET_DANAWA_KWD_DICT';
export const SET_ENURI_KWD_DICT = 'SET_ENURI_KWD_DICT';
export const SET_DANAWA_ANG_DICT = 'SET_DANAWA_ANG_DICT';
export const SET_ENURI_ANG_DICT = 'SET_ENURI_ANG_DICT';